
[General]
	#受缚时可以使用的指令
	tiedAllowedCommand = ["gamemode", "hojojutsu norp", "w", "msg", "tell", "hojojutsu chat"]
	#自定义材质图床域名白名单
	whitelistHost = ["pic.xiaobuawa.top", "pasteboard.co", "gcdnb.pbrd.co", "booru.my-board.org", "www.booru.my-board.org", "imgur.com", "s.namemc.com", "i.imgur.com", "discord.com", "discordapp.net", "minecraftskins.com", "i.ibb.co", "i.postimg.cc", "www.minecraftskins.com", "kbmc005.com", "www.kbmc005.com"]
	#使用指令norp的通报范围(0为无视距离) -格
	#Range: > 0
	norpMessageRadius = 64
	#使用指令norp后的冷却时间 -tick
	#Range: > 0
	norpCoolDown = 3600
	#第一次norp冷却结束后，第二次norp的有效时间，超时则变回第一次norp -tick
	#Range: > 600
	norpConfirmDuration = 1200
	#norp解除束缚之后，玩家不能被绑的时间 -tick
	#Range: > 0
	norpDuration = 1200

