
[ars_nouveau]

	[ars_nouveau.imbuement]
		enable = true

	[ars_nouveau.enchantment]
		enable = true

	[ars_nouveau.enchanting_apparatus]
		enable = true

[maidsoulkitchen_maidsoulkitchen]

	[maidsoulkitchen_maidsoulkitchen.consume_water_from_multi]
		enable = true

	[maidsoulkitchen_maidsoulkitchen.consume_water_from_single]
		enable = true

	[maidsoulkitchen_maidsoulkitchen.item_use]
		enable = true

[maid_storage_manager]

	[maid_storage_manager.smithing]
		enable = true

	[maid_storage_manager.brewing]
		enable = true
		count = 3

	[maid_storage_manager.stripping]
		enable = true

	[maid_storage_manager.tacz]
		enable = true

	[maid_storage_manager.altar]
		enable = true

	[maid_storage_manager.furnace]
		enable = true

	[maid_storage_manager.watering]
		bucket = true
		enable = true
		bottle = true

	[maid_storage_manager.craft]
		enable = true

	[maid_storage_manager.stone_cutting]
		enable = true

[maidsoulkitchen_farmersdelight]

	[maidsoulkitchen_farmersdelight.cutting]
		enable = true

	[maidsoulkitchen_farmersdelight.campfire_cooking_from_hand]
		enable = true

	[maidsoulkitchen_farmersdelight.campfire_cooking]
		enable = true

	[maidsoulkitchen_farmersdelight.cooking]
		enable = true

	[maidsoulkitchen_farmersdelight.skillet]
		enable = true

[maidsoulkitchen_miners_delight]

	[maidsoulkitchen_miners_delight.cooking]
		enable = true

[maidsoulkitchen_vintagedelight]

	[maidsoulkitchen_vintagedelight.fermenting]
		enable = true

